### PR TITLE
New option for custom Flash Projector Name + Anti Rock System

### PR DESCRIPTION
**Pull request by AzukiMPGH**
Basically, commit 5ee19a5a
I reverted all of the changes on commit 3a163c0 and 4e8b6b3 since I didn't see fit for spending more time trying to work things out. I might bring back the bag thing though since it worked surprisingly well.
Anti rock system *should* be in place with the commit  78da452

### CODE REVIEW

**Comment by iObsidian** [comment]
You should make it that rocks are non solid or something, sometiems the bot gets stuck

**Comment by AzukiMPGH** [comment]
Yeah I've noticed that too, I'm gonna write a thing that just replaces all the rocks with nothing when the map loads

**Comment by AlanBaumgartner** [comment]
Another idea is that since the bot gets stuck on lava with safe walk on, you could have a lava check and move out of it so that way when the train crosses lava you follow along but wont continue to stand in it if for some reason the train stops nearby it.

**Comment by thomas-crane** [comment]
I will have a closer look at this when I'm home from Uni. My only concern is that while the bot may not be _totally_ undetectable, walking straight through rocks makes it much more detectable and provides hard evidence of hacking if someone is recording.  I think we should implement rock/lava avoidance in a similar way to how I implemented enemy avoidance (see 984e84d5b78a842c53ccf099344e136a6e9592e4)

**Comment by AzukiMPGH** [comment]
I guess so, but something like that shouldn't be harder as well. Just add every rock to a list (or dictionary however you roll) and then just calculate the shortest and best way around it.

**Comment by AlanBaumgartner** [comment]
I wouldn't worry much about it being undetectable either, the only way you get banned is by someone recording and walking thru walks is less obvious than the 5-10 accounts all doing the same exact thing. The rocks could be desync.

**Comment by AzukiMPGH** [comment]
Alrighty, I took the enemy avoidance system, changed and tweaked a tiny bit and now it's a rock avoidance system, whoop. I did a *TINY* amount of testing, I don't know how this will fare in the long run, but it seemed like it was working for the time being. PLEASE report bugs etc. cuz I'm not gonna be able to test for 24/7.

**Comment by thomas-crane** [comment]
Awesome, thanks for your work. I'll test this out first thing tomorrow morning and merge it in if all goes well

**Comment by AzukiMPGH** [comment]
Thanks again! I should've fixed the things you told me to in this commit b18dea8

**Comment by AzukiMPGH** [comment]
I noticed some strange behavior when being close to a rock, the bot with seemingly stop moving until going away from that rock.

**Comment by AzukiMPGH** [comment]
I thoroughly tested the rock avoidance movement behavior and noticed that it avoids rocks without any further issues.

**Comment by thomas-crane** [comment]
Closing because
 - I added rock avoidance (and gave credit) but want to review some of the other features which were in this request (mainly the flash projector name setting)

Thanks again for your work on this! I will credit you in the next release on mpgh.

**Pull request closed without merging**
