### PR TITLE
Fix for 'realm is full' spam

### PR DESCRIPTION
**Pull request by iObsidian**
Reworked portal handling to avoid realm is full message and at the same time fucked the formatting

### CODE REVIEW

**Comment by thomas-crane** [comment]
I can't even send PMs on MPGH until I have 15 posts so I'll have to reply through here.
I'm not sure what IDE you're using but it's probably just easiest if you adjust the settings to match the project's settings while you're working on it. It's a bit of an inconvenience but will stop this from happening in the future too

**Comment by AzukiMPGH** [comment]
I dunno if you have ReSharper or not Alde, but if you have you can edit the settings around to have the same formatting as the original project.

**Comment by iObsidian** [comment]
Yes @AzukiMPGH I have ReSharper. @thomas-crane what settings do you use? Defaults without resharper?

**Comment by thomas-crane** [comment]
Yeah VS2015 defaults.
Closing this one but please open a new request when the formatting is not an issue. Also, C# naming conventions say that methods should start with an uppercase, so just change getPortalFromData to GetPortalFromData.

**Comment by iObsidian** [comment]
Thank you :) I'm very new to C#, coming from Java.

**Pull request closed without merging**
